### ISSUE TITLE
Unclear provenance warning solution is unclear

### ISSUE THREAD

**Issue by davidchisnall** [jeremysinger/capabilitiesforcoders#1]
The proposed fix here (splitting it into two parts) is still somewhat unclear. The provenance comes from the left in the &=, but it also (by default) comes from the left in the & expression.

The best way of fixing an unclear provenance warning is to explicitly cast one of the provenance-carrying values to a provenance-free type. `a & ((ptraddr_t)b)` would be the clearest fix here because it conveys intentionality: you are adding `a` (as a provenance-carrying type) with the address of `b`.

**Comment by jeremysinger** [comment]
This is addressed in #3
